from .dados_serializer import *
from .pedagogo_serializer import *
from .coordenadorCurso_serializer import *
from .aluno_serializer import *
from .ataDeAcompanhamento_serializer import *
from .componenteCurricular_serializer import *
from .curso_serializer import *
from .disciplina_serializer import *
from .documentacaoComplementar_serializer import *
from .parecer_serializer import *
from .professor_seralizer import *
from .PEIPeriodoLetivo_serializer import *
from .pei_central_serializer import *