from .parecer import *
from .PEIPeriodoLetivo import *
from .professor import *
from .aluno import *
from .coordenadorCurso import *
from .pedagogo import *
from .componenteCurricular import *
from .curso import *
from .disciplina import *
from .pei_central import *
from .componenteCurricular import *
from .ataDeAcompanhamento import *
from .documentacaoComplementar import *
from .userNapne import *
from .notificacao import *