from .parecer import *
from .PEIPeriodoLetivo import *
from .aluno import *
from .componenteCurricular import *
from .curso import *
from .disciplina import *
from .pei_central import *
from .componenteCurricular import *
from .ataDeAcompanhamento import *
from .documentacaoComplementar import *
from .notificacao import *
from .usuario import *
from .registration_request import *
