# Generated by Django 5.2.5 on 2025-09-18 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEIPeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('periodo', models.CharField(choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='SEMESTRE', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(100)])),
                ('categoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'A matrícula deve conter apenas números')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Tu tem 1000 caracteres para escrever', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('data', models.DateField(auto_now_add=True)),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='pei.peiperiodoletivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='pei.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
