# Generated by Django 5.2.5 on 2025-09-19 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeiCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_do_aluno', models.TextField(help_text='Histórico do aluno', validators=[django.core.validators.MinLengthValidator(200)], verbose_name='Histórico Escolar')),
                ('necessidades_educacionais_especificas', models.TextField(help_text='Detalhar as condições do estudante o que ele necessita. Ex: Se o estudante é cego: sua condição é: cegueira. Precisa de: Braille, Leitor de telas...', validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Necessidades Educacionais Especificas')),
                ('habilidades', models.TextField(help_text='Conhecimentos, Habilidades, Capacidades, Interesses, Necessidades (O que sabe? Do que gosta/afinidades?...)', validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Afinidades (habilidades, conhecimentos ...)')),
                ('dificuldades_apresentadas', models.TextField(help_text='Dificuldades apresentadas', validators=[django.core.validators.MinLengthValidator(30)], verbose_name='Dificuldades apresentadas')),
                ('adaptacoes', models.TextField(blank=True, help_text='Adaptações Razoáveis e/ou Acessibilidades Curriculares', verbose_name='Adaptações Razoáveis e/ou Acessibilidades Curriculares')),
                ('status_pei', models.CharField(choices=[('CREATED', 'Aberto'), ('INPROGRESS', 'Em Andamento'), ('CLOSED', 'Concluído')], help_text='Status Atual', max_length=10, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(100)])),
                ('categoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
