# Generated by Django 5.2.5 on 2025-11-04 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name=django.core.validators.MinLengthValidator(7)),
        ),
    ]
