# Generated by Django 5.2.5 on 2025-10-16 16:51

import django.core.validators
import pei.managers.arquivo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacaocomplementar',
            name='caminho',
        ),
        migrations.AddField(
            model_name='documentacaocomplementar',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentacoes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg']), pei.managers.arquivo.validate_file_size]),
        ),
    ]
