# Generated by Django 5.2.5 on 2025-11-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pei', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nome',
        ),
    ]
