# Generated by Django 5.0 on 2025-11-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pei', '0002_alter_aluno_email_alter_aluno_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
    ]
