from .dados_serializer import *
from .pedagogo_serializer import *
from .coordenador_curso_serializer import *
from .aluno_serializer import *
from .ata_de_acompanhamento_serializer import *
from .componente_curricular_serializer import *
from .curso_serializer import *
from .disciplina_serializer import *
from .documentacao_complementar_serializer import *
from .parecer_serializer import *
from .professor_seralizer import *
from .pei_periodo_letivo_serializer import *
from .pei_central_serializer import *