from .aluno_serializer import *
from .ataDeAcompanhamento_serializer import *
from .componenteCurricular_serializer import *
from .curso_serializer import *
from .disciplina_serializer import *
from .documentacaoComplementar_serializer import *
from .parecer_serializer import *
from .PEIPeriodoLetivo_serializer import *
from .pei_central_serializer import *
from .notificacao_serializer import *
from .usuario_serializer import *
from .conteudo_serializer import *
from .acompanhamento_serializer import *
