<<<<<<< Updated upstream
# Generated by Django 5.2.5 on 2025-10-01 00:48
=======
# Generated by Django 5.2.5 on 2025-09-30 22:28
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=100)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
