# Generated by Django 5.2.5 on 2025-09-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='usuario',
        ),
    ]
