from .dados_view_set import DadosViewSet
from .disciplina_view_set import DisciplinaSerializer
from .curso_view_set import CursoViewSet
from .aluno_view_set import AlunoViewSet
from .ata_de_acompanhamento_view_set import AtaDeAcompanhamentoViewSet
from .componente_curricular_view_set import ComponenteCurricularViewSet
from .coordenador_curso_view_set import CoordenadorCursoViewSet
from .documentacao_complementar_view_set import DocumentacaoComplementarViewSet
from .professor_view_set import ProfessorViewSet
from .pei_periodo_letivo_view_set import PEIPeriodoLetivoViewSet
from .pedagogo_view_set import PedagogoViewSet
from .parecer_view_set import ParecerViewSet

